version = 1

[[fileilters]]
pattern = "**/*.js"
exclude = ["node_modules/**"]

[[fileilters]]
pattern = "**/*.vue"
exclude = ["node_modules/**"]

[[fileilters]]
pattern = "**/*.ts"
exclude = ["node_modules/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.javascript]
  plugins = ["eslint"]
  environment = ["browser", "es2022"]
  runtime = "v8"
  
  [analyzers.javascript.plugins.eslint]
  config_path = ".eslintrc.json"
