version = 1

# Exclude JavaScript/Vue/TypeScript files that are handled by ESLint in GitHub Actions
[fileilters.default]
exclude = ["**/*.js", "**/*.vue", "**/*.ts"]

[[analyzers]]
name = "javascript"
enabled = false
