name: JavaScript Code Quality

on:
  pull_request:
  # Allow manual triggering
  workflow_dispatch:
  # Allow other workflows (e.g. Publish) to invoke this one.
  workflow_call:


env:
  fail-fast: true


permissions:
  contents: read


jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v7.2.2

    - name: Set up Node.js
      uses: actions/setup-node@1a1c0f6084d9304168f6c4f4a2bbb6f4a2bf24eb # v4.1.0
      with:
        node-version: lts/*

    - name: Install pnpm
      uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0
      with:
        version: 9

    - name: Restore Node.js dependencies cache
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      id: cache-restore
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile

    - name: Save Node.js dependencies cache
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Run ESLint
      run: pnpm run lint:js
