name: Shell Code Quality

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  fail-fast: true

permissions:
  contents: read

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Run ShellCheck
      run: |
        # Project utility scripts (use of bash or compatible assumed)
        find lib/dojo-src utils -type f -name '*.sh' -exec \
          docker run --rm -v "$PWD:/mnt" -w /mnt koalaman/shellcheck:stable --severity=warning --shell=bash {} +
